# Build customization
builds:
  - binary: lure
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

# Archive customization
archives:
  - format: binary

    format_overrides:
      - goos: windows
        format: zip

    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

    replacements:
      darwin: macOS

    files:
      - nothing.*

# GitHub release customization
release:
  draft: true
  prerelease: true